# Generated by Django 3.2.8 on 2021-10-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
